### ISSUE TITLE
Support for database configuration in XML

### ISSUE THREAD

**Issue by kghmanuel** [marklogic/marklogic-data-hub#1084]
#### The issue

ml-gradle supports defining database in either XML or JSON format. The current support in DHF is in JSON. Attempting to use an XML configuration such as the following would fail:

```
<database-properties xmlns="http://marklogic.com/manage">
  <database-name>data-hub-FINAL</database-name>
  <geospatial-element-pair-indexes>
    <geospatial-element-pair-index>
      <parent-namespace-uri/>
      <parent-localname>Employee</parent-localname>
      <latitude-namespace-uri/>
      <latitude-localname>latitude</latitude-localname>
      <longitude-namespace-uri/>
      <longitude-localname>longitude</longitude-localname>
      <coordinate-system>wgs84</coordinate-system>
      <range-value-positions>false</range-value-positions>
      <invalid-values>reject</invalid-values>
    </geospatial-element-pair-index>
  </geospatial-element-pair-indexes>
</database-properties>
```

#### Tech details

Which Operating System are you using? Windows 7

Which version of MarkLogic are you using? 9.0-5

Which version of the Data Hub Framework are you using? 3.0.0

Is this a QuickStart UI bug? If so, which browser are you using? Not Likely. Chrome.

#### The devil is in the details...

Stacktrace as follows:

```
[Step 16 of 41]  com.marklogic.hub.deploy.commands.DeployHubOtherDatabasesCommand
java.lang.RuntimeException: Unable to read JSON from file: D:\Vanguard\ML Tutorials\dhf\code\user-config\databases\data-hub-FINAL.xml
	at com.marklogic.rest.util.JsonNodeUtil.mergeJsonFiles(JsonNodeUtil.java:22)
	at com.marklogic.hub.deploy.commands.DeployHubDatabaseCommand.mergeDatabaseFiles(DeployHubDatabaseCommand.java:135)
	at com.marklogic.hub.deploy.commands.DeployHubDatabaseCommand.getPayload(DeployHubDatabaseCommand.java:106)
	at com.marklogic.hub.deploy.commands.DeployHubDatabaseCommand.buildPayload(DeployHubDatabaseCommand.java:101)
	at com.marklogic.hub.deploy.commands.DeployHubDatabaseCommand.execute(DeployHubDatabaseCommand.java:79)
	at com.marklogic.hub.deploy.commands.DeployHubOtherDatabasesCommand.execute(DeployHubOtherDatabasesCommand.java:46)
	at com.marklogic.hub.deploy.HubAppDeployer.deploy(HubAppDeployer.java:75)
	at com.marklogic.hub.impl.DataHubImpl.install(DataHubImpl.java:317)
	at com.marklogic.quickstart.service.DataHubService.install(DataHubService.java:57)
	at com.marklogic.quickstart.service.DataHubService$$FastClassBySpringCGLIB$$4c244452.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669)
	at com.marklogic.quickstart.service.DataHubService$$EnhancerBySpringCGLIB$$85512556.install(<generated>)
	at com.marklogic.quickstart.web.CurrentProjectController.install(CurrentProjectController.java:90)
	at com.marklogic.quickstart.web.CurrentProjectController$$FastClassBySpringCGLIB$$1ef23de5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.marklogic.quickstart.web.CurrentProjectController$$EnhancerBySpringCGLIB$$b141e240.install(<generated>)
...
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: D:\Vanguard\ML Tutorials\dhf\code\user-config\databases\data-hub-FINAL.xml; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
```

Note that running `gradle mldeploydatabases` succeeds without any error.

**Comment by grechaw** [comment]
@popzip well, yeah techincally it is.  JSON-first is the philosophy of DHF and it makes a lot of assumptions along those lines.  For every XML payload there is an equivalent JSON one, it's just a pain to transform between them.  One thing that can help is to get an existing config from the server in json format, then move the values from the XML into the JSON.

**Comment by aebadirad** [comment]
Going forward, json declarations will be used as the standard to eliminate supporting both and documenting both and training on both.

Apologies to XML users out there, but we need to pick a configuration format and json is just lighter weight for the types of declarations we have in data hub. You can still use xml and xpath for all your data needs though!
