### ISSUE TITLE
QS crashes with an NPE

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/marklogic-data-hub#1207]
This is DHF/QS on Windows 7 with Chrome. I see this on the develop branch. IDK if it exists in 3.0.

I have repeatedly had QS crash with an NPE when switching between projects and adding/removing them. I don't have reproducible steps yet. I've already spent a couple hours trying to pin this down and just don't have more time to devote to it right now. I want to capture the error info, though, in case it is useful.

What all scenarios have in common are that I have logged out and switched projects at least once, and I have either created a new project or removed an old one, or both in the same session.

In the UI, it manifests as the entities tab displaying nothing (and a 500 error reported in the Chrome dev tools). I think this is just collateral damage from the following error reported by the server on port 8080:
```
15:21:53.999 [http-nio-8080-exec-7] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet
] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with r
oot cause
java.lang.NullPointerException: null
        at com.marklogic.quickstart.service.FlowManagerService.lambda$getFlows$2(FlowManagerService.java:86)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.marklogic.quickstart.service.FlowManagerService.getFlows(FlowManagerService.java:99)
        at com.marklogic.quickstart.service.EntityManagerService.getEntities(EntityManagerService.java:114)
        at com.marklogic.quickstart.web.EntitiesController.getEntities(EntitiesController.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableH
andlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMapping
HandlerAdapter.java:877)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandl
erAdapter.java:783)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.j
ava:158)
```
I clipped the stack trace, on the assumption a hundred more frames down inside spring and apache catalina weren't going to help much.

I will also attach the chrome dev tools console log in case it points any fingers to a precursor problem.

**Comment by kcoleman-marklogic** [comment]
Log from Chrome dev tools console

[QS_no_entities.log](https://github.com/marklogic/marklogic-data-hub/files/2225721/QS_no_entities.log)

**Comment by grechaw** [comment]
the stack trace is excellent info.

**Comment by aebadirad** [comment]
This should now be resolved.
