### ISSUE TITLE
Error running hadoop

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#121]
It looks like we are dependent on running from the quick-start developer directory:

15:16:18.769 [http-nio-8080-exec-5] DEBUG c.m.hub.service.EntityManagerService - Entity : consumer
15:16:32.756 [pool-1-thread-1] DEBUG c.marklogic.contentpump.ContentPump - Command: IMPORT
15:16:32.757 [pool-1-thread-1] DEBUG c.marklogic.contentpump.ContentPump - Arguments: -mode local -host localhost -port 8010 -username admin -password admin -input_file_path C:\Users\dfeldman\Documents\Projects\CMS-FFE\data\InsuranceApplications\insAppsOverlap -input_file_type documents -output_collections all -output_uri_replace "C:/Users/dfeldman/Documents/Projects/CMS-FFE/data/InsuranceApplications/insAppsOverlap,''" -transform_module /com.marklogic.hub/mlcp-flow-transform.xqy -transform_namespace http://marklogic.com/data-hub/mlcp-flow-transform -transform_param "<params><entity-name>consumer</entity-name><flow-name>insapp</flow-name><flow-type>input</flow-type></params>"
15:16:32.864 [pool-1-thread-1] DEBUG org.apache.hadoop.util.Shell - Failed to detect a valid hadoop home directory
java.io.IOException: Hadoop home directory C:\Projects\marklogic-data-hub\hadoop does not exist, is not a directory, or is not an absolute path.
        at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:312)
        at org.apache.hadoop.util.Shell.<clinit>(Shell.java:327)
        at org.apache.hadoop.util.GenericOptionsParser.preProcessForWindows(GenericOptionsParser.java:438)
        at org.apache.hadoop.util.GenericOptionsParser.parseGeneralOptions(GenericOptionsParser.java:484)
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:170)
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:153)
        at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:99)
        at com.marklogic.hub.DataHubContentPump.execute(DataHubContentPump.java:30)
        at com.marklogic.hub.Mlcp.loadContent(Mlcp.java:80)
        at com.marklogic.hub.web.controller.api.FlowApiController$3.run(FlowApiController.java:198)
        at com.marklogic.hub.service.TaskManagerService$TaskWrapper.run(TaskManagerService.java:103)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
15:16:32.866 [pool-1-thread-1] ERROR org.apache.hadoop.util.Shell - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
        at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:355)
        at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:370)

**Comment by divino** [comment]
I cannot re-create this issue. Please do note that unlike what is indicated in the logs, I am using mac.

1st Attempt: Manually Clearing of ML Datahub components using the the ML port 8001 web interface
- no errors encountered after running the quickstart to reinstall and until deployment of existing entities.

2nd Attempt: Using the "Uninstall" button of Quickstart
- no errors encountered after running the quickstart to reinstall and until deployment of existing entities.

Kindly provide more info to help in replicating the issue.

**Comment by damonfeldman** [comment]
I think this is windows specific.

This is a blocker because if I run from my build directory from marklogic-data-hub/quick-start it is OK, but if I simply install the .jar somewhere and try to run it fails. Here is today's stack trace from running purely off the jar:


08:39:19.799 [pool-1-thread-1] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService
08:39:20.135 [pool-1-thread-1] INFO  com.marklogic.hub.Mlcp - [import, -mode, local, -host, localhost, -port, 8010, -username, admin, -password, admin, -generate_uri, true, -input_file_path, C:\Users\dfeldman\Documents\Projects\CMS-FFE\data\InsuranceApplications\insAppsOverlap, -input_file_type, documents, -output_collections, "consumer,all,input", -output_uri_replace, "C:/Users/dfeldman/Documents/Projects/CMS-FFE/data/InsuranceApplications/insAppsOverlap,''", -document_type, xml, -transform_module, /com.marklogic.hub/mlcp-flow-transform.xqy, -transform_namespace, http://marklogic.com/data-hub/mlcp-flow-transform, -transform_param, "<params><entity-name>consumer</entity-name><flow-name>all</flow-name><flow-type>input</flow-type></params>"]
08:39:26.423 [pool-1-thread-1] ERROR c.m.h.w.c.api.FlowApiController - Error encountered while trying to run flow:  consumer > all
java.io.IOException: Cannot load data from: C:\Users\dfeldman\Documents\Projects\CMS-FFE\data\InsuranceApplications\insAppsOverlap due to: Load data failed with:
Failed to locate the winutils binary in the hadoop binary path
        at com.marklogic.hub.Mlcp.loadContent(Mlcp.java:83)
        at com.marklogic.hub.web.controller.api.FlowApiController$3.run(FlowApiController.java:224)
        at com.marklogic.hub.service.TaskManagerService$TaskWrapper.run(TaskManagerService.java:104)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by HemantPuranik** [comment]
I am seeing the same issue as I am just following the tutorial on how to get started - by installing the jar file. Although I saw it once and as I am retrying it is not showing the Hadoop error but some other error. Will check if that needs another PR.
