### ISSUE TITLE
Failure to un-install the hub

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1392]
#### The issue
I started QuickStart-4.0.0 and it said things were not fully installed (likely because my earlier hub version put in the wrong triggers and/or jobs DBs)

This is in a new-ish directory, not the directory of an existing hub project, so it is trying to un-install the generic "data-hub" databases, rather than some named hub dbs.

The uninstall fails and ML 8002_ErrorLog.txt reports: 
```
2018-10-05 13:15:51.995 Info: ADMIN-DATABASEINUSE: (err:FOER0000) The following webdav-servers still refer to this database: data-hub-TRACING.
```

The Java log reports:
```
13:15:52.008 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.marklogic.quickstart.exception.DataHubException: Error in connecting to the Data Hub API with the following message: 500 Internal Server Error] with root cause
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:97)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)
	at com.marklogic.rest.util.MgmtResponseErrorHandler.handleError(MgmtResponseErrorHandler.java:26)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:766)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:724)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:698)
	at org.springframework.web.client.RestTemplate.delete(RestTemplate.java:563)
	at com.marklogic.mgmt.ManageClient.delete(ManageClient.java:300)
	at com.marklogic.mgmt.resource.AbstractResourceManager.deleteAtPath(AbstractResourceManager.java:189)
	at com.marklogic.mgmt.resource.AbstractResourceManager.delete(AbstractResourceManager.java:166)
	at com.marklogic.hub.deploy.commands.DeployHubDatabaseCommand.undo(DeployHubDatabaseCommand.java:96)
	at com.marklogic.hub.deploy.commands.DeployHubDatabasesCommand.undo(DeployHubDatabasesCommand.java:73)
	at com.marklogic.hub.deploy.HubAppDeployer.undeployAll(HubAppDeployer.java:245)
```

This is pretty good feedback. I obviously have an extra/old app server to un-deploy.

Some issues (minor)
1. I do not have any webdav servers, so I think this is my tracing HTTP server that was not removed (typo in error message). Might be in ml-gradle.
2. The process terminated with the uninstall window stuck at 67% or so, rather than reporting the issue.
3. There may be some process ordering problem where the tracing http server is not removed, or not removed if the prior install is 3.x.

Hub version 4.0.0

**Comment by damonfeldman** [comment]
Update on this

Workaround: I manually deleted the TRACING application server (HTTP) and tried to un-install again, and that worked fine.

Note that I was starting a brand new data hub, using the default "data-hub" names, and I had a previous 3.x hub installed. I bet the new 4.0 configuration does not use that app server, and because I did not run in the same directory as the old 3.x config there was no gradle entry for it. Therefore the un-install routine did not know it should be removed.

I think this is a corner case.

However: a more accurate error in the ML logs (HTTP server, not webdav) would be good, and that error should really bubble up to the Java error log (or at least tell you to go check the 8002_ErrorLog.txt for details on the error).

**Comment by grechaw** [comment]
This is a known one-time issue.  We didn't want to remove anything brutishly during upgrade, so the tracing db is still around.

Agreed on bubbling up the error and having mitigation.  Similar issues will accompany future upgrades, so having a solution would be good for now and later.

**Comment by grechaw** [comment]
I'll make sure Shannon can evaluate where to take this issue.  I'm leaning toward side-stepping this issue entirely by taking provisioning out of the DHF.
