### ISSUE TITLE
If you call your input flow "input", it doesn't work (v4.1.0)

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#1709]
#### The issue

If you call your input flow "input", it doesn't work (v4.1.0)

#### Tech details

OS: Mac
ML Version: 9.0-7
DHF Version: 4.1.0

#### The devil is in the details...

From quickstart UI

12:30:02.281 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.marklogic.client.ResourceNotFoundException: Local message: Could not read resource at resources/ml:flow. Server Message: The requested flow was not found] with root cause
com.marklogic.client.ResourceNotFoundException: Local message: Could not read resource at resources/ml:flow. Server Message: The requested flow was not found
        at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4313)
        at com.marklogic.client.impl.OkHttpServices.getIteratedResourceImpl(OkHttpServices.java:3098)
        at com.marklogic.client.impl.OkHttpServices.getIteratedResource(OkHttpServices.java:3075)
        at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:61)
        at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:57)

**Comment by ayuwono** [comment]
Fixed and passed qa
