### ISSUE TITLE
if you call your mapping "mapping", it doesn't work (v4.1.0)

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#1710]
#### The issue

if you call your mapping "mapping", it doesn't work. The quickstart UI doesn't display anything

#### Tech details

OS: Mac
ML Version: 9.0-7
DHF Version: 4.1.0
Browser: Chrome

#### The devil is in the details...

from quickstart ui log

13:15:30.479 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NumberFormatException: For input string: "0..json"] with root cause
java.lang.NumberFormatException: For input string: "0..json"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.marklogic.hub.impl.MappingManagerImpl.getMappingVersion(MappingManagerImpl.java:162)
        at com.marklogic.hub.impl.MappingManagerImpl.getMappingVersion(MappingManagerImpl.java:146)
        at com.marklogic.hub.impl.MappingManagerImpl.getMappings(MappingManagerImpl.java:136)
        at com.marklogic.quickstart.service.MappingManagerService.getMappings(MappingManagerService.java:62)

**Comment by ayuwono** [comment]
Fixed and passed qa
