### ISSUE TITLE
DHF 5.0.0: Duplicate range-element-index

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2510]
#### The issue
I have create two entities and checked the items in both as indexed. They will contain the same data types and will be used to join data.

The UI allows me to add the two index items. The backend allows the two items to be deployed.

![image](https://user-images.githubusercontent.com/1315891/57721463-421b6c00-7652-11e9-85a5-b565f2763344.png)

`2019-05-14 14:08:00.842 ERROR 61732 --- [nio-8080-exec-8] c.m.rest.util.MgmtResponseErrorHandler   : Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"ADMIN-DUPLICATECONFIGITEM", "message":"ADMIN-DUPLICATECONFIGITEM: (err:FOER0000) Database resource 'data-hub-5.0-STAGING' already contains 'Database 'range-element-index''"}}
14:08:00.842 [http-nio-8080-exec-8] ERROR c.m.r.util.MgmtResponseErrorHandler - Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"ADMIN-DUPLICATECONFIGITEM", "message":"ADMIN-DUPLICATECONFIGITEM: (err:FOER0000) Database resource 'data-hub-5.0-STAGING' already contains 'Database 'range-element-index''"}}
2019-05-14 14:08:00.842 ERROR 61732 --- [nio-8080-exec-8] c.m.m.r.databases.DatabaseManager        : Error occurred while sending PUT request to /manage/v2/databases/data-hub-5.0-STAGING/properties; logging request body to assist with debugging: {"path-namespace":[{"prefix":"es","namespace-uri":"http://marklogic.com/entity-services"}],"range-element-index":[{"collation":"http://marklogic.com/collation/codepoint","invalid-values":"reject","localname":"city","namespace-uri":null,"range-value-positions":false,"scalar-type":"string"},{"collation":"http://marklogic.com/collation/codepoint","invalid-values":"reject","localname":"state","namespace-uri":null,"range-value-positions":false,"scalar-type":"string"},{"collation":"http://marklogic.com/collation/codepoint","invalid-values":"reject","localname":"city","namespace-uri":null,"range-value-positions":false,"scalar-type":"string"},{"collation":"http://marklogic.com/collation/codepoint","invalid-values":"reject","localname":"state","namespace-uri":null,"range-value-positions":false,"scalar-type":"string"}],"uri-lexicon":true,"triple-index":true,"triggers-database":"data-hub-5.0-staging-TRIGGERS","collection-lexicon":true,"schema-database":"data-hub-5.0-staging-SCHEMAS"}
14:08:00.842 [http-nio-8080-exec-8] ERROR c.m.m.r.databases.DatabaseManager - Error occurred while sending PUT request to /manage/v2/databases/data-hub-5.0-STAGING/properties; logging request body to assist with debugging: {"path-namespace":[{"prefix":"es","namespace-uri":"http://marklogic.com/entity-services"}],"range-element-index":[{"collation":"http://marklogic.com/collation/codepoint","invalid-values":"reject","localname":"city","namespace-uri":null,"range-value-positions":false,"scalar-type":"string"},{"collation":"http://marklogic.com/collation/codepoint","invalid-values":"reject","localname":"state","namespace-uri":null,"range-value-positions":false,"scalar-type":"string"},{"collation":"http://marklogic.com/collation/codepoint","invalid-values":"reject","localname":"city","namespace-uri":null,"range-value-positions":false,"scalar-type":"string"},{"collation":"http://marklogic.com/collation/codepoint","invalid-values":"reject","localname":"state","namespace-uri":null,"range-value-positions":false,"scalar-type":"string"}],"uri-lexicon":true,"triple-index":true,"triggers-database":"data-hub-5.0-staging-TRIGGERS","collection-lexicon":true,"schema-database":"data-hub-5.0-staging-SCHEMAS"}
org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:79)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:124)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
	at com.marklogic.rest.util.MgmtResponseErrorHandler.handleError(MgmtResponseErrorHandler.java:26)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:598)
	at com.marklogic.mgmt.ManageClient.putJson(ManageClient.java:115)
	at com.marklogic.mgmt.AbstractManager.putPayload(AbstractManager.java:65)
	at com.marklogic.mgmt.resource.databases.DatabaseManager.putPayload(DatabaseManager.java:42)
	at com.marklogic.mgmt.resource.AbstractResourceManager.updateResource(AbstractResourceManager.java:140)
	at com.marklogic.mgmt.resource.AbstractResourceManager.save(AbstractResourceManager.java:87)
	at com.marklogic.appdeployer.command.databases.DeployDatabaseCommand.execute(DeployDatabaseCommand.java:129)
	at com.marklogic.hub.deploy.commands.DeployHubDatabaseCommand.execute(DeployHubDatabaseCommand.java:69)
	at com.marklogic.appdeployer.command.databases.DeployOtherDatabasesCommand.execute(DeployOtherDatabasesCommand.java:81)
	at com.marklogic.appdeployer.impl.AbstractAppDeployer.executeCommand(AbstractAppDeployer.java:111)
	at com.marklogic.hub.deploy.HubAppDeployer.executeCommand(HubAppDeployer.java:78)
	at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractAppDeployer.java:70)
	at com.marklogic.hub.deploy.HubAppDeployer.deploy(HubAppDeployer.java:58)
	at com.marklogic.hub.impl.DataHubImpl.install(DataHubImpl.java:533)
	at com.marklogic.hub.web.service.DataHubService.install(DataHubService.java:70)
	at com.marklogic.hub.web.service.DataHubService$$FastClassBySpringCGLIB$$65ce96e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.marklogic.hub.web.service.DataHubService$$EnhancerBySpringCGLIB$$c802ce9b.install(<generated>)
	at com.marklogic.hub.web.web.CurrentProjectController.install(CurrentProjectController.java:92)
	at com.marklogic.hub.web.web.CurrentProjectController$$FastClassBySpringCGLIB$$e7cbedf3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.marklogic.hub.web.web.CurrentProjectController$$EnhancerBySpringCGLIB$$804aafb8.install(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:919)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter$$FastClassBySpringCGLIB$$510f8b9a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.marklogic.hub.web.auth.ConnectionAuthenticationFilter$$EnhancerBySpringCGLIB$$471dffb6.doFilter(<generated>)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:151)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)`

#### Tech details

Which Operating System are you using?
MacOS 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Partially UI and backend

**Comment by prestonmcgowan** [comment]
Removing the duplicate index on an entity allowed the Redeploy Hub to succeed.

**Comment by prestonmcgowan** [comment]
UI/Backend needs some better protections against this action

**Comment by rjrudin** [comment]
@prestonmcgowan There is an internal issue for this in JIRA - 2496 - that I have a PR for. So it's a known issue that will be fixed on the backend.

**Comment by aebadirad** [comment]
Fixed in 5.0.1
