### ISSUE TITLE
When one item fails in a harmonize batch run, other items in the chunk do not get processed

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#279]
I ran a harmonize flow of 4 documents, one of which failed due to the triples plugin returning sem:triple xml instead of a primitive sem:triple sequence. Only the trace for the single failing item was persisted. Also (see other issue) only the triples plugin was traced.

This is a Java stack around that time:
10:40:08.703 [SimpleAsyncTaskExecutor-1] ERROR o.s.batch.core.step.AbstractStep - Encountered an error executing step step1 in job Harmonize
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/flow: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $func($identifier, $content, $headers, $options) -- Invalid coercion: xs:untypedAtomic("http://datahub/David_Perez_17077388349996699028http://www.w3.org...") as sem:triple . See the MarkLogic server error log for further detail.
    at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4626)
    at com.marklogic.client.impl.JerseyServices.postIteratedResourceImpl(JerseyServices.java:4074)
    at com.marklogic.client.impl.JerseyServices.postIteratedResource(JerseyServices.java:4004)
    at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:100)
    at com.marklogic.spring.batch.hub.FlowWriter.write(FlowWriter.java:41)
    at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
    at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
    at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
    at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
    at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
    at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
    at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
    at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
    at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
    at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
    at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
    at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
    at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
    at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
    at com.sun.proxy.$Proxy93.execute(Unknown Source)
    at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
    at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:392)
    at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
    at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
    at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
    at java.lang.Thread.run(Thread.java:745)

**Comment by paxtonhare** [comment]
@damonfeldman Looking at this again.. It seems like the reason it bailed out was because the error happened in the hub core code and not in the plugin code. I vote we close this. Dunno if we need to open another ticket that says something like make hub better at handling invalid output from plugins.
