### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rawalpuneet** [marklogic/marklogic-data-hub#298]
I am never able to get pass this issue on my mac. I am sure i'm missing something obvious. Can anyone point me to it?

I get this error while running input flow for acme tech. No documents are loaded and no errors are reported on the UI. 

11:47:33.023 [http-nio-8080-exec-3] WARN  o.s.c.a.ConfigurationClassEnhancer - @Bean method ScopeConfiguration.stepScope is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
11:47:33.024 [http-nio-8080-exec-3] WARN  o.s.c.a.ConfigurationClassEnhancer - @Bean method ScopeConfiguration.jobScope is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
11:47:33.028 [http-nio-8080-exec-3] INFO  c.m.s.b.h.StagingConfig$$EnhancerBySpringCGLIB$$cce6e087 - Connecting to MarkLogic via: [admin@centos2:8010]
11:47:36.401 [http-nio-8080-exec-3] INFO  c.m.s.b.h.StagingConfig$$EnhancerBySpringCGLIB$$cce6e087 - Connecting to MarkLogic JobRepository via: [admin@centos2:8013]
11:47:36.401 [http-nio-8080-exec-3] INFO  c.m.c.spring.DatabaseClientManager - Connecting to REST server with: [admin@centos2:8010]
11:47:38.177 [http-nio-8080-exec-3] INFO  c.m.c.spring.DatabaseClientManager - Connecting to REST server with: [admin@centos2:8010]
11:47:38.222 [http-nio-8080-exec-3] INFO  c.m.c.spring.DatabaseClientManager - Connecting to REST server with: [admin@centos2:8010]
11:47:38.292 [http-nio-8080-exec-3] INFO  c.m.s.b.c.s.JobRepositoryConfigurer - Initializing MarkLogic JobRepository implementation
11:47:38.292 [http-nio-8080-exec-3] INFO  c.m.c.spring.DatabaseClientManager - Connecting to REST server with: [admin@centos2:8013]
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.marklogic.quickstart.service.FlowManagerService.buildJobParameters(FlowManagerService.java:153)
	at com.marklogic.quickstart.service.FlowManagerService.runMlcp(FlowManagerService.java:163)
	at com.marklogic.quickstart.web.EntitiesController.runInputFlow(EntitiesController.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by paxtonhare** [comment]
Did you upgrade from a previous version of the hub? If so, please read the [CHANGELOG](https://github.com/marklogic/marklogic-data-hub/releases/tag/v1.0.0-rc.5) for super important info about upgrading.

Here is the important part:

# WARNING! Breaking changes.

Make sure to uninstall your existing hub first (Settings -> Uninstall)
Remove the .tmp directory from your project directory
Remove the marklogic_config, build.gradle, gradle.properties, gradle-local.properties files

**Comment by rawalpuneet** [comment]
it was a fresh install.

**Comment by paxtonhare** [comment]
Just for fun, please remove the .tmp directory and try it again. The error indicates that you have an old, cached version of mlcp options and not current options.

**Comment by rawalpuneet** [comment]
Excellent! 
That was it. Thanks for the help.

**Comment by paxtonhare** [comment]
I'm curious how you had stuff in your .tmp folder if it was a fresh install.

**Comment by rawalpuneet** [comment]
I had data-hub installed before but I emptied the dir with rm -rf * which doesn't delete .tmp. I should have explained that before.
