### ISSUE TITLE
Scaffolding generation failed

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#338]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

I created an Input flow and a Harmonize for an entity, but both failed.
The Input flow had no plugins, and only the content directory.
The Harmonize flow had all three directories, but the content.xqy was missing. I had selected the option to crete the transform from the entity defiinition.

Which Operating System are you using?
Mac OS X 

Which version of MarkLogic are you using?
ML 9 ea3

Which version of the Data Hub Framework are you using?
2.0-alpha.1

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:
16:29:37.005 [SimpleAsyncTaskExecutor-15] INFO  c.m.a.impl.SimpleAppDeployer - Deployed app data-hub
16:29:37.127 [SimpleAsyncTaskExecutor-15] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: DataHubService.installUserModules took 3.519109557s
16:38:39.029 [SimpleAsyncTaskExecutor-16] INFO  com.marklogic.mgmt.ManageClient - Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: admin, admin username: admin]
16:38:56.615 [http-nio-8080-exec-8] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.marklogic.client.FailedRequestException: Local message: failed to read resource at resources/scaffold-content: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: Extension scaffold-content does not exist. . See the MarkLogic server error log for further detail.] with root cause
com.marklogic.client.FailedRequestException: Local message: failed to read resource at resources/scaffold-content: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: Extension scaffold-content does not exist. . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4626)
	at com.marklogic.client.impl.JerseyServices.getIteratedResourceImpl(JerseyServices.java:3269)
	at com.marklogic.client.impl.JerseyServices.getIteratedResource(JerseyServices.java:3214)
	at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:62)
	at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:58)
	at com.marklogic.hub.scaffold.Scaffolding$ContentPlugin.getContents(Scaffolding.java:276)
	at com.marklogic.hub.scaffold.Scaffolding.createFlow(Scaffolding.java:97)
	at com.marklogic.quickstart.service.EntityManagerService.createFlow(EntityManagerService.java:180)
	at com.marklogic.quickstart.web.EntitiesController.createFlow(EntitiesController.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by damonfeldman** [comment]
![image](https://cloud.githubusercontent.com/assets/700633/20903617/ff8d67ea-bb09-11e6-86d6-411d2fbac701.png)

Here is the incomplete directory tree, where you can see that the directories were created, but none of the plugins.

**Comment by damonfeldman** [comment]
This is the entity model
![image](https://cloud.githubusercontent.com/assets/700633/20903664/357d121a-bb0a-11e6-8ca9-eb6d8ee8f28f.png)

**Comment by damonfeldman** [comment]
Note the claim entity was hand edited to repair from a prior bug (probably irrelevant, since it says a service does note exist)

**Comment by paxtonhare** [comment]
Did you just drop the new beta hub in on top of another existing hub?

I should have said that you should do an uninstall first.

**Comment by damonfeldman** [comment]
closing
