### ISSUE TITLE
Returning json:object() isn't invoking ES serialization in flow

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#345]
Version 2.0:

The code to detect whether to treat the plugin response as ES vs non-ES is set to look at map:map vs anything else. The true test should be on if $type is a key in the map/object returned.

Right now if you return an object, which is the default from the generated code, it will not work.

**Comment by damonfeldman** [comment]
Some stack traces from the logs that may be relevant:

MarkLogic log (8010):
2016-12-13 16:31:36.136 Notice: in /MarkLogic/json/custom.xqy, at 404:3,
2016-12-13 16:31:36.136 Notice: in json-custom:element-qname-from-json-name#2(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:
xsi="http://www.w3.org/2001/XMLSchema-instance" .../>...XDMP-ATOMIZEFUNC: (err:FOTY0013) Functions cannot be atomized...), "$type") [1.0-ml]
2016-12-13 16:31:36.136 Notice:   $config = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSch
ema-instance" .../>...XDMP-ATOMIZEFUNC: (err:FOTY0013) Functions cannot be atomized...)
2016-12-13 16:31:36.136 Notice:   $json_name = "$type"



QuickStart Java log:
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/flow: Internal Server Error. Server Message: XDMP-QNAMELEXFORM: fn:QName("", "$type") -- Invalid lexical form for QName . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4626)
	at com.marklogic.client.impl.JerseyServices.postIteratedResourceImpl(JerseyServices.java:4074)
	at com.marklogic.client.impl.JerseyServices.postIteratedResource(JerseyServices.java:4004)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:100)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:96)
	at com.marklogic.spring.batch.hub.FlowWriter.write(FlowWriter.java:36)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262)
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:268)
	at java.lang.Thread.run(Thread.java:745)
