### ISSUE TITLE
Illegal/unsupported escape sequence in Windows 10 when creating entities

### ISSUE THREAD

**Issue by qhreul** [marklogic/marklogic-data-hub#406]
v2.0.0-alpha.4

```shell
10:35:07.109 [SimpleAsyncTaskExecutor-11] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected error occurred invoking async method 'public void com.marklogic.quickstart.service.DataHubService.reinstallUserModules(com.marklogic.hub.HubConfig,com.marklogic.quickstart.listeners.DeployUserModulesListener,com.marklogic.quickstart.listeners.ValidateListener)'.
com.marklogic.quickstart.exception.DataHubException: Error in connecting to the Data Hub API with the following message: Illegal/unsupported escape sequence near index 13
C:\Workspace\mlworld\plugins\entities[/\\][^/\\]+$
             ^
        at com.marklogic.quickstart.service.DataHubService.reinstallUserModules(DataHubService.java:99)
        at com.marklogic.quickstart.service.DataHubService$$FastClassBySpringCGLIB$$4c244452.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 13
C:\Workspace\mlworld\plugins\entities[/\\][^/\\]+$
             ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.escape(Unknown Source)
        at java.util.regex.Pattern.atom(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.matches(Unknown Source)
        at java.lang.String.matches(Unknown Source)
        at com.marklogic.hub.deploy.commands.LoadUserModulesCommand$1.preVisitDirectory(LoadUserModulesCommand.java:117)
        at com.marklogic.hub.deploy.commands.LoadUserModulesCommand$1.preVisitDirectory(LoadUserModulesCommand.java:98)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at com.marklogic.hub.deploy.commands.LoadUserModulesCommand.execute(LoadUserModulesCommand.java:98)
        at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractAppDeployer.java:63)
        at com.marklogic.hub.DataHub.runCommands(DataHub.java:287)
        at com.marklogic.hub.DataHub.installUserModules(DataHub.java:269)
        at com.marklogic.quickstart.service.DataHubService.installUserModules(DataHubService.java:197)
        at com.marklogic.quickstart.service.DataHubService.reinstallUserModules(DataHubService.java:96)
        ... 7 common frames omitted
```

**Comment by jmakeig** [comment]
Seems to be a general issue on Windows 10.

**Comment by jmakeig** [comment]
Smells like something in https://github.com/marklogic/marklogic-data-hub/blob/2.0-develop/marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java#L96-L141.

**Comment by dmcassel** [comment]
Seen with OpenJDK 1.8.0_131-b11

**Comment by dmcassel** [comment]
Error went away when using Oracle JDK 1.8.0_31.
