### ISSUE TITLE
DHF 5.2.2: TDEs not created and SQL does not work after an Entity was created in Quick Start

### ISSUE THREAD

**Issue by ls2013** [marklogic/marklogic-data-hub#4178]
[SQL] SQL-TABLENOTFOUND: Unknown table: Table '.Project' not found
Stack Trace
At line 1 column 14:
In xdmp:sql("select * from Project;", ())

1. select * from Project;

In undefined on line 4
In xdmp:eval("import module namespace amped-qconsole = &quot;http://marklogic....", (fn:QName("","query"), "select * from Project;"), <options xmlns="xdmp:eval"><database>16883106843478996903</database>...</options>)
-----------------
DataHub Log:
17:26:58.271 [SimpleAsyncTaskExecutor-1339] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public v
oid com.marklogic.hub.web.service.DataHubService.installUserModulesAsync(com.marklogic.hub.HubConfig,boolean,com.marklogic.hub.web.listeners.DeployUserModule
sListener,com.marklogic.hub.web.listeners.ValidateListener)
com.marklogic.hub.web.exception.DataHubException: Error in connecting to the Data Hub API with the following message: java.net.ConnectException: Failed to co
nnect to localhost/0:0:0:0:0:0:0:1:8011
        at com.marklogic.hub.web.service.DataHubService.installUserModules(DataHubService.java:113)
        at com.marklogic.hub.web.service.DataHubService.installUserModulesAsync(DataHubService.java:100)
        at com.marklogic.hub.web.service.DataHubService$$FastClassBySpringCGLIB$$65ce96e0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)

**Comment by akshaysonvane** [comment]
Do you see the ".tdex" file in the final/staging schemas database?
If the file's present then you should be able to query the view using a user that has "data-hub-operator" role.

**Comment by ls2013** [comment]
I went back to DH 5.1.0 and it started working. 
    On Monday, July 6, 2020, 06:49:19 PM EDT, Akshay Sonvane <notifications@github.com> wrote:  
 
 


Do you see the ".tdex" file in the final/staging schemas database?
If the file's present then you should be able to query the view using a user that has "data-hub-operator" role.

**Comment by akshaysonvane** [comment]
Closing this since you don't see the issue anymore. 
@ls2013 please reopen if this happens again.
