### ISSUE TITLE
/config/query write failed.....XDMP-FIELDRIDXNOTFOUND: cts:field-reference("datahubSourceName", ())

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#5479]
### Deploy failure
```
[marklogic@marklogic10a]$  gradle mlDeploy
```
```
> Task :hubPreInstallCheck
PreInstall check: [PASSED]
> Task :mlDeleteModuleTimestampsFile
Module timestamps file /mldhf/Med/build/ml-javaclient-util/local-module-timestamps.properties does not exist, so not deleting
Error occurred while loading modules; host: localhost; port: 7119; cause: Local message: /config/query write failed: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Operation results in invalid Options: XDMP-FIELDRIDXNOTFOUND: cts:field-reference("datahubSourceName", ()) -- No  field range index for "datahubSourceName" collation=http://marklogic.com/collation/ coordinate-system=wgs84
com.marklogic.client.FailedRequestException: Local message: /config/query write failed: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Operation results in invalid Options: XDMP-FIELDRIDXNOTFOUND: cts:field-reference("datahubSourceName", ()) -- No  field range index for "datahubSourceName" collation=http://marklogic.com/collation/ coordinate-system=wgs84
        at com.marklogic.client.impl.OkHttpServices.putPostValueImpl(OkHttpServices.java:2938)
        at com.marklogic.client.impl.OkHttpServices.putValue(OkHttpServices.java:2796)
        at com.marklogic.client.impl.QueryOptionsManagerImpl.writeOptions(QueryOptionsManagerImpl.java:158)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$installQueryOptions$3(DefaultModulesLoader.java:585)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$executeTask$5(DefaultModulesLoader.java:622)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

> Task :mlDeployApp FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> java.net.ConnectException: Failed to connect to localhost/127.0.0.1:7117
```

### HWOS & Server version:
```
- Operating System = CentOS 8@VMWare
- MarkLogic = 10.0-6.2
- Data Hub = v5.2.6 | v5.4.2 (same error message with v5.2.6 or v5.4.2)
```

### Additional details
During the Undeploy, database server experienced intermittent disruption:

![ml-8001-error1](https://user-images.githubusercontent.com/53400797/113803945-65ea6e00-9712-11eb-9090-90d596398a97.jpg)

![ml-8001-error2](https://user-images.githubusercontent.com/53400797/113803950-697df500-9712-11eb-9792-6fb561d79180.jpg)

**Comment by chenfiona** [comment]
Found a workaround.   Thanks!
