### ISSUE TITLE
Cryptic error: broken pipe logging into wrong port from Hub Central

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#5875]
I started Hub Central (5.4.4) with the wrong port mappings and got a cryptic error that took some time to run down. 

Ideal behavior would be: "Could not connect to a MarkLogic Server instance on port 8010" but acceptable would be something to the effect that a connection failed or timed out. 

The okhttp library unfortunately reports "unexpected end of stream" with "\n not found" instead:

```

2021-07-08 09:31:51.521 [http-nio-8080-exec-9] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

com.marklogic.client.MarkLogicIOException: java.io.IOException: unexpected end of stream on http://localhost:8010/...

at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:716)

at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:709)

at com.marklogic.client.impl.OkHttpServices.access$300(OkHttpServices.java:129)

at com.marklogic.client.impl.OkHttpServices$CallRequestImpl.lambda$executeRequest$1(OkHttpServices.java:5685)

at com.marklogic.client.impl.OkHttpServices.sendRequestWithRetry(OkHttpServices.java:744)

at com.marklogic.client.impl.OkHttpServices.sendRequestWithRetry(OkHttpServices.java:721)

at com.marklogic.client.impl.OkHttpServices.access$4000(OkHttpServices.java:129)

at com.marklogic.client.impl.OkHttpServices$CallRequestImpl.executeRequest(OkHttpServices.java:5690)

at com.marklogic.client.impl.OkHttpServices$CallRequestImpl.withDocumentResponse(OkHttpServices.java:5614)

at com.marklogic.client.impl.BaseProxy$DBFunctionRequest.responseSingle(BaseProxy.java:904)

at com.marklogic.hub.dataservices.HubCentralService$1HubCentralServiceImpl.getAuthorities(HubCentralService.java:68)

at com.marklogic.hub.dataservices.HubCentralService$1HubCentralServiceImpl.getAuthorities(HubCentralService.java:62)

at com.marklogic.hub.central.auth.AuthenticationFilter.authenticateUser(AuthenticationFilter.java:91)

at com.marklogic.hub.central.auth.AuthenticationFilter.attemptAuthentication(AuthenticationFilter.java:63)

at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)

at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)

at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)

at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)

at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)

at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)

at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)

at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)

at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)

at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)

at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)

at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)

at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)

at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)

at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)

at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

at java.base/java.lang.Thread.run(Thread.java:835)

Caused by: java.io.IOException: unexpected end of stream on http://localhost:8010/...

at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)

at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)

at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)

at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)

at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)

at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)

at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)

at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:49)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)

at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)

at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)

at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:714)

... 65 common frames omitted

Caused by: java.io.EOFException: \n not found: limit=0 content=…

at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:348)

at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)

at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)

... 81 common frames omitted
```

**Comment by rjrudin** [comment]
Can you file this as an issue at https://github.com/marklogic/java-client-api instead? It's not practical for a client of the ML Java Client to try/catch for this on every single call made using the Java Client; tools like ml-gradle would need to do the same thing too. It'd be much easier and more useful for the Java Client to catch an IOException and add the context you're looking for, and then every user of the Java Client would benefit from it.
